### ISSUE TITLE
API request failed

### ISSUE THREAD

**Issue by arthursoficial** [multimodalart/grog#5]
Firstly, great job. This is something I've been searching for for years!

The space works perfectly, I managed to host it on Hugging Face. The problem is that the API request doesn't work; I've tried using cURL and Python, but nothing works. Unlike other spaces, this one returns errors (when making the API call) such as "ValueError: 'The submission failed! Error: 422'" in Colab and ValueError: Unsupported protocol: sse_v2 in my Flask on Replit.

Below is the code I tried to execute in Colab:

```
from gradio_client import Client

client = Client("https://amazonaws-sp-high-resolution-controlnet-tile.hf.space/")
result = client.predict(
		"Hello!!",	# str  in 'Prompt' Textbox component
		"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# filepath  in 'Image' Image component
		2048,	# Literal[2048, 2560]  in 'resolution' Dropdown component
		3,	# float  in 'Resemblance' Number component
		3,	# float  in 'Creativity' Number component
		3,	# float  in 'Hdr' Number component
		"DDIM",	# Literal[DDIM, DPMSolverMultistep, K_EULER_ANCESTRAL, K_EULER]  in 'scheduler' Dropdown component
		3,	# float  in 'Steps' Number component
		0.1,	# float (numeric value between 0.1 and 30) in 'Guidance Scale' Slider component
		3,	# float  in 'Seed' Number component
		"Hello!!",	# str  in 'Negative Prompt' Textbox component
		True,	# bool  in 'Guess Mode' Checkbox component
							api_name="/predict"
)
print(result)
```

**Comment by apolinario** [comment]
I think this issue is best reported at Hugging Face discussion forum as it is not an error with Grog https://discuss.huggingface.co
